# Generated by Django 5.1.6 on 2025-10-22 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_purchased', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
